- src/pages/Accounts/AccountModal.tsx
- src/pages/Accounts/Accounts.tsx
> Kevin feature

- src/components/TransactionsTable/TransactionsTable.tsx
- src/pages/Transactions/Transactions.tsx
Updated the layout on the Transactions page by adding a header, select options, and enhancing the UI with a TransactionsTable component. The TransactionsTable component displays a list of transactions
> Refactor Transactions page and add TransactionsTable component

- src/pages/Accounts/Accounts.tsx
net cash layout and edit/delete buttons added
> insight layout and edit/delete

- package-lock.json
- src/App.tsx
- src/main.tsx
- src/pages/Tax/EmployerInfoStep.tsx
- src/pages/Tax/FinancialInformationStepW2.tsx
- src/pages/Tax/PersonalInfoStep.tsx
- src/pages/Tax/ReviewAndSubmitStepW2.tsx
- src/pages/Tax/Tax.tsx
- src/pages/Tax/TaxEditView.tsx
- src/pages/Tax/TaxTable.tsx
- src/pages/Tax/W2EditView.tsx
- src/pages/Tax/W2Slice.ts
- src/pages/Tax/WithholdingsAndMiscW2.tsx
- src/store/Store.tsx
Created General Tax Form layout involving two tables, an All Active Tax Forms table and Archived Tax Forms Table
Active Tax Forms can be edited or deleted, Archived Tax Forms can only be viewed
created basic form layout with Redux Store Persistence
> Joseph tax layout

- src/layouts/LandingLayout.tsx
- src/pages/AuthenticationPages/Login.tsx
- src/pages/AuthenticationPages/Register.tsx
- src/pages/Landing/LandingPage.tsx
* Added a feature section
* Removed different color background from login/register pages
* Added a small indicator to suggest OAuth is an alternative login/register method
> FRO-21: Landing Page

- .gitignore
- .prettierrc
- .vscode/extensions.json
- .vscode/settings.json
- src/pages/Accounts/Accounts.tsx
- src/types/models.ts
- src/utils/helpers.ts
added some global workspace settings + prettier config
> Fetch account information from API in accounts Page + improvements

- src/pages/Transactions/Transactions.tsx
- src/utils/transactionService.ts
The commit encompasses a significant refactoring of the Transactions.tsx page to enhance abstraction and minimize redundancy. Transaction data is fetched from the backend using a new utility 'transactionService.ts', specifically through the 'getTransactionByUserId' function. Added a new function 'deleteTransaction' in the same utility to allow transaction deletion by ID.
> Refactor Transactions page and add transactionService utility

- src/components/CategoryIcon.tsx
- src/pages/Spending/Spending.tsx
- src/pages/Spending/SpendingMonth.tsx
- src/types/models.ts
change enum to lowercase, update spending files to use category enum from model.ts
> Fix spending page

- src/pages/Transactions/Transactions.tsx
The Transactions page now includes more sophisticated filtering options, allowing users to filter transactions by specific date ranges and amounts. Furthermore, sorting features have been implemented which allow transactions to be ordered by either date or amount, in ascending or descending order.
> Added advanced filtering and sorting to Transactions page

- src/pages/Transactions/Transactions.tsx
- src/utils/transactionService.ts
Updated Transactions.tsx to add functionality for creating a new transaction through a form in the modal. Also made minor adjustments to various filters and inputs. The transactionService.ts file has been updated to include an API call function for creating transactions.
> Added create transaction functionality

- src/pages/Accounts/AccountModal.tsx
- src/pages/Accounts/Accounts.tsx
- src/pages/Accounts/CreditScoreModal.tsx
credit score report modal created for viewing credit report
> credit report modal

- src/locales/en.json
- src/locales/es.json
- src/pages/Transactions/Transactions.tsx
- src/utils/transactionService.ts
The Transactions.tsx file has been substantially refactored to clean up code. Import lines have been compressed for clarity and unnecessary comments removed. String double quotes have been replaced with single quotes for consistency. Additionally, the endpoints for TRANSACTIONS_API_URL and ACCOUNTS_API_URL in transactionService.ts have been updated to use the gatway. Adjustments to app localization were also made to add more translations for both English and Spanish languages.
> Refactor Transactions.tsx and update APIs endpoints

- src/pages/Transactions/Transactions.tsx
- src/utils/transactionService.ts
Implemented transaction editing feature and added transaction validation logic.
> Add transaction editing and validation features

- src/index.css
- src/pages/Transactions/Transactions.tsx
Updated the Transactions page, adding category icons with differentiated colors. Implemented improved form styling for a better user experience.
> Enhance Transactions page with category colors and improved form styling

- src/components/LandingFooter.tsx
- src/components/LandingHeader.tsx
- src/pages/AuthenticationPages/Login.tsx
Made IDs relevant to the Login page.
> Placing ids/login

- src/components/NavBar.tsx
> placing-ids/navbar

- src/pages/AuthenticationPages/Register.tsx
> Add IDs to Register.tsx

- package-lock.json
- package.json
- src/pages/Budgets/components/BudgetsComponent.tsx
- src/pages/Budgets/components/SummaryComponent.tsx
- src/pages/Budgets/components/modals/DeleteBucketModal.tsx
- src/pages/Budgets/components/modals/DeleteBudgetModal.tsx
- src/pages/Budgets/components/modals/EditBucketModal.tsx
- src/pages/Budgets/components/modals/EditBudgetModal.tsx
- src/pages/Budgets/components/modals/EditSpendingBudgetModal.tsx
- src/pages/Budgets/components/modals/NewBucketModal.tsx
- src/pages/Budgets/components/modals/NewBudgetModal.tsx
included IDs to various elements in the budgets page.
> Budgets Page Adding IDs

- src/pages/Misc/ErrorPage.tsx
Added two new IDs to the Error Page
1. ID for h1 tag
2. ID for "Return to homepage" button
> Error page add ids

- jest.config.js
- package-lock.json
- package.json
- src/__tests__/spending.test.tsx
- tsconfig.json
- Added jest dependencies and `/__tests__` folder in `/src` folder to hold tests. 
- Coverage is also configured. It currently checks for coverage in every .ts/.tsx file in the `/scr` folder but there are plans to add more specific details to what needs coverage.
- Configured a `jest.config.js` file.
> base jest setup with a starting test file for spending page

- .gitignore
- jest.config.js
- src/__mocks__/imageMock.ts
- src/__mocks__/styleMock.ts
- src/__testSetup__/setupFile.ts
- src/__tests__/landing.test.tsx
- src/__tests__/reviewSection.test.tsx
Also adds a working initial render of landing page jest tests
>  Mock folder and Setup Folder for everyones use 

- src/__tests__/spending.test.tsx
- src/pages/Spending/Spending.tsx
93% stmt cov
72% branch cov
90% funct cov
92% line cov
note: had to create and remove old branch ran into some issues on my local.
> added spendings test

- package-lock.json
- src/__tests__/spendingMonth.test.tsx
Statement coverage: 92 
Branch coverage: 68.96
Function coverage: 84.84
Line coverage: 92.3
> Added jest testing for SpendingMonth

- src/__tests__/spending.test.tsx
added more varied transaction items to cover more branches.
stmt: 97%
branch: 100%
funcs: 90%
lines: 96%
> added more coverage to spending.test

- __tests__/spending.test.tsx
- src/pages/Spending/Spending.tsx
suppressed act() warnings
added data-testids to elements in Spendings.tsx
> refactor code and added coverage to spendings.test.tsx

- __tests__/FinancialInformationStepW2.test.tsx
[+] Added test for save and handleChange function's errors. 
[+] Coverage: 97.22 statement, 64.28 branch, 85.71 functions, 100 line
[-] removed duplicate getOtherIncomeAPI mock
> Increased FinancialInformationStepW2 coverage to above 80%

- __tests__/w2Step.test.tsx
- src/pages/Tax/w2Step.tsx
Cannot reach full branch coverage, missing error implementation for:
employer, wages, federalIncomeTaxWithheld, stateIncomeTaxWithheld, w2socialSecurityTaxWithheld, w2medicareTaxWithheld
Cannot reach line 101 in W2Step.tsx:
checks for undefined id but id is automatically set when previous W2s are fetched or new empty W2 is created.
> W2 step jest/d swe

- src/components/__tests__/budgets/ReservedMoniesInput.test.tsx
[+] Added jest test to ReservedMoniesInput
[+] Tested for Increment and decrement value, and input element's onChange
[+] Coverage: 100% statement, line, branch, function
> AndyZheng430/ReservedMoniesInput Added Jest tests
